# -*- coding: utf-8 -*-
"""allFinViz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CkikPgZONXHSvMrNUxZRXbUCCA3GWf-Y
"""

__author__ = 'tomrunner21'

import requests
from requests import get
import pandas as pd
import numpy as np

from bs4 import BeautifulSoup as soup
from urllib.request import Request, urlopen

pages = np.arange(21,8241,20)
stocks = []

def allFinViz():

  url = ("https://finviz.com/screener.ashx")
  req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})
  webpage = urlopen(req).read()
  html = soup(webpage, "html.parser")

  tickers = html.find_all(attrs = {'class': 'screener-link-primary'})
  for ticker in tickers:
    stocks.append(ticker.get_text().strip())

  for page in pages:
    url = ("https://finviz.com/screener.ashx?v=111&r=" + str(page))
    req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    webpage = urlopen(req).read()
    html = soup(webpage, "html.parser")

    tickers = html.find_all(attrs = {'class': 'screener-link-primary'})
    for ticker in tickers:
      stocks.append(ticker.get_text().strip())
  return stocks
